=== 3-X/RLHD/schemas/environments.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "environments.schema.json",
  "title": "Environments",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "key": {
        "type": "string",
        "description": "Identifier used for accessing specific environments from code."
      },
      "area": {
        "type": "string",
        "description": "The area the environment should apply in."
      },
      "description": {
        "type": "string",
        "description": "Optional description of what this changes or why."
      },
      "isPohTheme": {
        "type": "boolean",
        "description": "Whether the environment is for a player-owned house theme."
      },
      "isUnderwater": {
        "type": "boolean",
        "description": "Whether the environment is for an underwater area, such as Guardians of the Rift."
      },
      "force": {
        "type": "boolean",
        "description": "Whether to force the environment to apply, even if atmospheric lighting is disabled."
      },
      "allowSkyOverride": {
        "type": "boolean",
        "description": "Whether to allow overriding the sky with default sky."
      },
      "lightningEffects": {
        "type": "boolean",
        "description": "Whether the area should have flashing lightning effects."
      },
      "allowRoofShadows": {
        "type": "boolean",
        "description": "Whether the area should allow roof shadows to be drawn. Defaults to true."
      },
      "instantTransition": {
        "type": "boolean",
        "description": "Whether transitions to and from this area should always be instant."
      },
      "ambientColor": {
        "type": [ "string", "array" ],
        "description": "Ambient light color in sRGB, specified as a hex color code or an array in the range 0-255. Accepts decimals.",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "minItems": 3,
        "maxItems": 3,
        "items": {
          "type": "number"
        }
      },
      "ambientStrength": {
        "type": "number",
        "description": "Ambient light strength multiplier. Defaults to 1."
      },
      "directionalColor": {
        "type": [ "string", "array" ],
        "description": "Directional light color in sRGB, specified as a hex color code or an array in the range 0-255. Accepts decimals.",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "minItems": 3,
        "maxItems": 3,
        "items": {
          "type": "number"
        }
      },
      "directionalStrength": {
        "type": "number",
        "description": "Directional light strength multiplier. Defaults to 0.25."
      },
      "waterColor": {
        "type": [ "string", "array" ],
        "description": "Water color in sRGB, specified as a hex color code or an array in the range 0-255. Accepts decimals.",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "minItems": 3,
        "maxItems": 3,
        "items": {
          "type": "number"
        }
      },
      "waterCausticsColor": {
        "type": [ "string", "array" ],
        "description": "Water caustics color in sRGB (as hex or array). Defaults to the environment's directional light color.",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "minItems": 3,
        "maxItems": 3,
        "items": {
          "type": "number"
        }
      },
      "waterCausticsStrength": {
        "type": "number",
        "description": "Water caustics strength. Defaults to the environment's directional light strength."
      },
      "underglowColor": {
        "type": [ "string", "array" ],
        "description": "Underglow color in sRGB (as hex or array). Acts as light emanating from the ground.",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "minItems": 3,
        "maxItems": 3,
        "items": {
          "type": "number"
        }
      },
      "underglowStrength": {
        "type": "number",
        "description": "Underglow strength multiplier. Acts as light emanating from the ground."
      },
      "sunAngles": {
        "type": "array",
        "description": "The sun's altitude and azimuth specified in degrees in the horizontal coordinate system. Altitude is from the ground up, azimuth is clockwise from north.",
        "items": [
          {
            "type": "number",
            "minimum": 0,
            "maximum": 90
          },
          {
            "type": "number",
            "minimum": 0,
            "maximum": 360
          }
        ]
      },
      "fogColor": {
        "type": [ "string", "array" ],
        "description": "Sky/fog color in sRGB, specified as a hex color code or an array in the range 0-255. Accepts decimals.",
        "pattern": "^#[A-Fa-f0-9]{6}$",
        "minItems": 3,
        "maxItems": 3,
        "items": {
          "type": "number"
        }
      },
      "fogDepth": {
        "type": "number",
        "description": "Fog depth normally ranging from 0 to 100, which combined with draw distance decides the fog amount. Defaults to 25."
      },
      "groundFogStart": {
        "type": "integer",
        "description": "Only matters with groundFogOpacity > 0. Specified in local units (1 tile = 128 units), where zero is the lowest height, and larger negative numbers are further up. Defaults to -200."
      },
      "groundFogEnd": {
        "type": "integer",
        "description": "Only matters with groundFogOpacity > 0. Specified in local units (1 tile = 128 units), where zero is the lowest height, and larger negative numbers are further up. Defaults to -500."
      },
      "groundFogOpacity": {
        "type": "number",
        "description": "Ground fog opacity ranging from 0 to 1, meaning no ground fog and full ground fog respectively. Defaults to 0."
      },
      "windAngle": {
        "type": "number",
        "description": "Angle in degrees for the wind direction. Zero is east and positive rotates towards north. Defaults to 0."
      },
      "windSpeed": {
        "type": "number",
        "description": "Controls wind turbulence; the rate of change in the wind noise. Larger values cause more rapid changes. Defaults to 15."
      },
      "windStrength": {
        "type": "number",
        "description": "Strength of the displacement caused by wind; the maximum amount a single vertex is allowed to move. Defaults to 0."
      },
      "windCeiling": {
        "type": "number",
        "description": "The height where the `windStrength` will be reached. The closer objects are to this height, the stronger the wind will be. Defaults to 1280 (10 tiles in height)."
      }
    }
  }
}

=== 3-X/RLHD/src/main/resources/rs117/hd/scene/environments.json
[
  {
    "area": "EVIL_BOB_ISLAND",
    "ambientColor": "#c0ae94",
    "ambientStrength": 3,
    "directionalColor": "#f5bc67",
    "directionalStrength": 1.25,
    "fogColor": "#b8d6ff",
    "fogDepth": 60
  },
  {
    "area": "REVENANT_CAVES",
    "ambientColor": "#aecfc9",
    "ambientStrength": 3,
    "directionalColor": "#aecfc9",
    "directionalStrength": 1,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#081f1c",
    "fogDepth": 20
  },
  {
    "area": "RANDOM_EVENT_GRAVEDIGGER",
    "ambientColor": "#5a8cc0",
    "ambientStrength": 3,
    "directionalColor": "#5a8cc0",
    "directionalStrength": 0.75,
    "fogColor": "#1e314b",
    "fogDepth": 40,
    "groundFogStart": -150,
    "groundFogEnd": -350,
    "groundFogOpacity": 0.5
  },
  {
    "area": "BLACK_ROOMS",
    "allowSkyOverride": false,
    "ambientColor": "#97baff",
    "ambientStrength": 3,
    "directionalStrength": 0,
    "fogDepth": 65
  },
  {
    "area": "FROZEN_WASTE_PLATEAU",
    "ambientColor": "#3b87e4",
    "ambientStrength": 0.4,
    "directionalColor": "#8a9eb6",
    "directionalStrength": 2.5,
    "fogColor": "#252c37",
    "fogDepth": 80
  },
  {
    "area": "Corporeal Beast Lair",
    "ambientStrength": 0.75,
    "directionalStrength": 0.1,
    "fogDepth": 25
  },
  {
    "area": "Lucien's Base Environment",
    "ambientColor": "#D8EAFF",
    "ambientStrength": 1,
    "directionalColor": "#f4e5c9",
    "directionalStrength": 0.5,
    "fogColor": "#aebde0",
    "fogDepth": 70,
    "sunAngles": [
      68,
      190
    ]
  },
  {
    "area": "WILDERNESS_HIGH",
    "lightningEffects": true,
    "ambientColor": "#d7d2d2",
    "ambientStrength": 1,
    "directionalColor": "#c5b8b6",
    "directionalStrength": 1.75,
    "fogColor": "#101012",
    "fogDepth": 30,
    "groundFogStart": 0,
    "groundFogEnd": -250,
    "groundFogOpacity": 0.3,
    "windAngle": 40,
    "windSpeed": 10,
    "windStrength": 20
  },
  {
    "area": "WILDERNESS_LOW",
    "ambientColor": "#d7d2d2",
    "ambientStrength": 0.75,
    "directionalColor": "#8a9eb6",
    "directionalStrength": 2.5,
    "fogColor": "#3e3e46",
    "fogDepth": 20,
    "windAngle": 40,
    "windSpeed": 15,
    "windStrength": 40
  },
  {
    "area": "WILDERNESS_MID",
    "ambientColor": "#d7d2d2",
    "ambientStrength": 0.75,
    "directionalColor": "#c5b8b6",
    "directionalStrength": 2,
    "fogColor": "#25252a",
    "fogDepth": 30,
    "groundFogStart": 0,
    "groundFogEnd": -250,
    "groundFogOpacity": 0.3,
    "windAngle": 40,
    "windSpeed": 15,
    "windStrength": 25
  },
  {
    "area": "HUNTER_GUILD",
    "waterCausticsStrength": 50,
    "waterColor": "#0F1E38"
  },
  {
    "area": "Daimon's Crater - Bounty Hunter",
    "ambientColor": "#d7d2d2",
    "ambientStrength": 0.75,
    "directionalColor": "#c5b8b6",
    "directionalStrength": 2,
    "fogColor": "#25252a",
    "fogDepth": 30,
    "groundFogStart": 0,
    "groundFogEnd": -250,
    "groundFogOpacity": 0.3
  },
  {
    "area": "VARROCK_MUSEUM_BASEMENT",
    "ambientColor": "#b59b79",
    "ambientStrength": 2,
    "directionalStrength": 0.5,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#131b26",
    "fogDepth": 20
  },
  {
    "area": "STRONGHOLD_OF_SECURITY_WAR",
    "ambientColor": "#aaafb6",
    "ambientStrength": 1.5,
    "directionalStrength": 1,
    "sunAngles": [
      80,
      190
    ],
    "fogDepth": 45,
    "windSpeed": 10,
    "windStrength": 35
  },
  {
    "area": "STRONGHOLD_OF_SECURITY_FAMINE",
    "ambientColor": "#c0ae94",
    "ambientStrength": 1.3,
    "directionalColor": "#f5bc67",
    "directionalStrength": 1,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#544222",
    "fogDepth": 50
  },
  {
    "area": "STRONGHOLD_OF_SECURITY_PESTILENCE",
    "ambientColor": "#a2c35d",
    "ambientStrength": 1.5,
    "directionalStrength": 1,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#525e20",
    "fogDepth": 50,
    "groundFogStart": -150,
    "groundFogEnd": -300,
    "groundFogOpacity": 0.66
  },
  {
    "area": "STRONGHOLD_OF_SECURITY_DEATH",
    "ambientColor": "#542d22",
    "ambientStrength": 1.5,
    "directionalStrength": 1,
    "sunAngles": [
      80,
      190
    ],
    "fogDepth": 45
  },
  {
    "area": "TOLNA_DUNGEON_ANGER",
    "ambientColor": "#ae7d46",
    "ambientStrength": 1.3,
    "directionalColor": "#cb4848",
    "directionalStrength": 1.8,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#290000",
    "fogDepth": 40
  },
  {
    "area": "TOLNA_DUNGEON_FEAR",
    "ambientColor": "#77a0ff",
    "ambientStrength": 1.3,
    "directionalColor": "#4c78b6",
    "directionalStrength": 1.5,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#000b0f",
    "fogDepth": 40
  },
  {
    "area": "TOLNA_DUNGEON_CONFUSION",
    "ambientColor": "#77a0ff",
    "ambientStrength": 1.3,
    "directionalColor": "#4e9dd0",
    "directionalStrength": 1.5,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#2e0c23",
    "fogDepth": 40
  },
  {
    "area": "DORGESHKAAN",
    "directionalColor": "#a29b71",
    "directionalStrength": 1.5,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#190d02",
    "fogDepth": 40
  },
  {
    "area": "THE_INFERNO",
    "ambientColor": "#f0b8b8",
    "ambientStrength": 1.7,
    "directionalColor": "#fff6ca",
    "directionalStrength": 0.7,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#170b07",
    "fogDepth": 20,
    "underglowColor": "#ff0000",
    "underglowStrength": 2
  },
  {
    "area": "TZHAAR",
    "ambientColor": "#ffeacc",
    "ambientStrength": 0.8,
    "directionalColor": "#ffa400",
    "directionalStrength": 1.8,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#1a0808",
    "fogDepth": 15
  },
  {
    "area": "HALLOWED_SEPULCHRE_LOBBY",
    "ambientColor": "#c4d5ea",
    "ambientStrength": 0.7,
    "directionalColor": "#a0bbe2",
    "directionalStrength": 1,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#0d1012",
    "fogDepth": 50
  },
  {
    "area": "HALLOWED_SEPULCHRE_FLOOR_1",
    "ambientColor": "#9bbbb1",
    "ambientStrength": 0.9,
    "directionalColor": "#75e7ff",
    "directionalStrength": 1.8,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#111c1a",
    "fogDepth": 50
  },
  {
    "area": "HALLOWED_SEPULCHRE_FLOOR_2",
    "ambientColor": "#a0bfbf",
    "ambientStrength": 0.875,
    "directionalColor": "#74d6f7",
    "directionalStrength": 1.5,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#111c1b",
    "fogDepth": 50
  },
  {
    "area": "HALLOWED_SEPULCHRE_FLOOR_3",
    "ambientColor": "#a5c3cd",
    "ambientStrength": 0.85,
    "directionalColor": "#73c4f0",
    "directionalStrength": 1.5,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#121c1d",
    "fogDepth": 50
  },
  {
    "area": "HALLOWED_SEPULCHRE_FLOOR_4",
    "ambientColor": "#aac7dc",
    "ambientStrength": 0.825,
    "directionalColor": "#72b2e9",
    "directionalStrength": 1.5,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#121b1f",
    "fogDepth": 50
  },
  {
    "area": "HALLOWED_SEPULCHRE_FLOOR_5",
    "ambientColor": "#afcaea",
    "ambientStrength": 0.8,
    "directionalColor": "#71a0e2",
    "directionalStrength": 1.5,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#131b21",
    "fogDepth": 50
  },
  {
    "area": "VER_SINHAZA",
    "ambientColor": "#5a8cc0",
    "ambientStrength": 1.5,
    "directionalColor": "#67a8f8",
    "directionalStrength": 5,
    "fogColor": "#1e314b",
    "fogDepth": 40,
    "groundFogStart": -150,
    "groundFogEnd": -350,
    "groundFogOpacity": 0.5
  },
  {
    "description": "Needs to be above the non-legacy version",
    "key": "TOB_ROOM_VAULT_LEGACY",
    "area": "TOB_ROOM_VAULT",
    "ambientColor": "#7575ea",
    "ambientStrength": 3,
    "directionalColor": "#dda6a6",
    "directionalStrength": 1,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#0e081a",
    "fogDepth": 40
  },
  {
    "area": "TOB_ROOM_VAULT",
    "ambientColor": "#7575ea",
    "ambientStrength": 3,
    "directionalColor": "#dda6a6",
    "directionalStrength": 1,
    "sunAngles": [
      80,
      190
    ],
    "fogColor": "#040407",
    "fogDepth": 20
  },
  {
    "description": "Needs to be above the non-legacy version",
    "key": "THEATRE_OF_BLOOD_LEGACY",
    "area": "THEATRE_OF_BLOOD",
    "ambientColor": "#8282b0",
    "ambientStrength": 3,
    "directionalColor": "#dfc0c0",
    "directionalStrength": 5,
    "fogColor": "#0e0c2c",
    "fogDepth": 40
  },
  {
    "area": "THEATRE_OF_BLOOD",
    "ambientColor": "#8282b0",
    "ambientStrength": 3.5,
    "directionalColor": "#dfc0c0",
    "directionalStrength": 1.5,
    "fogColor": "#040407",
    "fogDepth": 40,
    "groundFogEnd": -1000,
    "groundFogStart": -200,
    "groundFogOpacity": 0.3
  },
  {
    "area": "TOA_LOOT_ROOM",
    "ambientStrength": 1.2,
    "directionalStrength": 0.5,
    "fogColor": "#050505",
    "fogDepth": 20
  },
  {
    "area": "TOA_ENTRANCE_LOBBY",
    "directionalStrength": 0.75,
    "fogColor": "#050505",
    "sunAngles": [
      125,
      180
    ],
    "fogDepth": 20
  },
  {
    "area": "TOMBS_OF_AMASCUT",
    "directionalStrength": 0.75,
    "fogColor": "#050505",
    "fogDepth": 20
  },
  {
    "area": "BARROWS_CRYPTS",
    "ambientColor": "#b58f7c",
    "ambientStrength": 3.5,
    "directionalColor": "#ffc875",
    "directionalStrength": 0,
    "groundFogOpacity": 1,
    "groundFogStart": -1900,
    "groundFogEnd": -2750,
    "instantTransition": true,
    "sunAngles": [
      80,
      190
    ],
    "fogDepth": 50
  },
  {
    "area": "BARROWS_TUNNELS",
    "ambientColor": "#b58f7c",
    "ambientStrength": 3,
    "directionalColor": "#ffc875",
    "directionalStrength": 0.5,
    "instantTransition": true,
    "sunAngles": [
      80,
      190
    ],
    "fogDepth": 30
  },
  {
    "area": "BARROWS",
